version: "2.1"
services:
  admin-hapi-mongo:
    container_name: admin-hapi-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: 'timeout 2 bash -c "</dev/tcp/localhost/27017"'
      interval: 5s
      timeout: 5s
      retries: 10
    # logging:
    #   driver: none